AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {{project-name}} - Production Lambda deployment

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string
    NoEcho: true

  JwtSecret:
    Type: String
    NoEcho: true
    Default: ""
    Description: JWT secret key (optional, only if using JWT auth)

  CorsAllowedOrigins:
    Type: String
    Default: '*'
    Description: Comma-separated list of allowed CORS origins

  LambdaMemorySize:
    Type: Number
    Default: 512
    Description: Lambda function memory size in MB

  LambdaTimeout:
    Type: Number
    Default: 30
    Description: Lambda function timeout in seconds

Conditions:
  HasJwtSecret: !Not [!Equals [!Ref JwtSecret, ""]]

Resources:
  # Lambda Function
  {{project-name | capitalize}}Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '{{project-name}}-prod'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/{{project-name}}:latest'
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Architectures:
        - x86_64
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Tags:
        Environment: production
        Application: {{project-name}}
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          RUST_LOG: info,{{project_name}}=debug
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref HttpApi
        RootHttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref HttpApi

  # HTTP API Gateway
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"

  # CloudWatch Log Groups
  ApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/{{project-name}}-prod
      RetentionInDays: 30

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${{{project-name | capitalize}}Function}'
      RetentionInDays: 30

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt {{project-name | capitalize}}Function.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/{{project-name}}'
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryUri'
